// Generated by ReScript, PLEASE EDIT WITH CARE


async function $$fetch() {
  return await import("./ReacttRace.res.js").then(function (m) {
              return m.run;
            });
}

export {
  $$fetch ,
}
/* ReacttRace Not a pure module */
