// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Prog = 2,
  Unit = 4,
  Id = 5,
  Bool = 6,
  Int = 7,
  String = 8,
  fun = 12,
  _let = 14,
  _in = 15,
  useState = 17,
  useEffect = 19,
  view = 21,
  _if = 23,
  then = 24,
  _else = 25,
  not = 28
