// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as ReactTraceBcJs from "./react-trace.bc.js";

function _run(prim0, prim1) {
  return ReactTraceBcJs.run(prim0, prim1);
}

function run(fuel, value) {
  try {
    var result = ReactTraceBcJs.run(fuel, value);
    Core__Option.forEach(result.checkpoints, (function (prim) {
            prim.reverse();
          }));
    return result;
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      console.error(e._1);
      return {
              error: "Runtime error"
            };
    }
    throw e;
  }
}

export {
  _run ,
  run ,
}
/* ./react-trace.bc.js Not a pure module */
