// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as ReactTraceBcJs from "./react-trace.bc.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function _run(prim0, prim1) {
  return ReactTraceBcJs.run(prim0, prim1);
}

function run(fuel, value) {
  try {
    let result = ReactTraceBcJs.run(fuel, value);
    Stdlib_Option.forEach(result.checkpoints, prim => {
      prim.reverse();
    });
    return result;
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === Stdlib_Exn.$$Error) {
      console.error(e._1);
      return {
        error: "Runtime error"
      };
    }
    throw e;
  }
}

export {
  _run,
  run,
}
/* ./react-trace.bc.js Not a pure module */
