'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Slider from "./shadcn-ui/Slider.res.js";
import * as Checkbox from "./shadcn-ui/Checkbox.res.js";
import * as Resizable from "./shadcn-ui/Resizable.res.js";
import * as ReacttRace from "../shared/react-trace/ReacttRace.res.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import ReactD3Tree from "react-d3-tree";
import * as HookLabelPlugin from "../shared/plugin/HookLabelPlugin.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import ReactCodemirror from "@uiw/react-codemirror";
import * as CodemirrorVim from "@replit/codemirror-vim";
import * as LangJavascript from "@codemirror/lang-javascript";
import * as LanguageJs from "../shared/syntax/language.js";
import * as CodemirrorThemeTokyoNightDay from "@uiw/codemirror-theme-tokyo-night-day";

var sample = "\nlet C x =\n  let (s, setS) = useState x in\n  if s = 42 then\n    setS (fun s -> s + 1);\n  s\n;;\nlet D _ =\n  let (s, setS) = useState true in\n  useEffect (setS (fun _ -> false));\n  [C 42, if s then 1 else 0]\n;;\nD ()\n".trim();

function useCenteredTree() {
  var match = React.useState(function () {
        return {
                x: 0,
                y: 0
              };
      });
  var setTranslate = match[1];
  var translate = match[0];
  var containerRef = function (container) {
    if (container === null || container === undefined) {
      return ;
    }
    var rect = container.getBoundingClientRect();
    var width = rect.width;
    var height = rect.height;
    var x = width / 2;
    var y = height / 10;
    if (translate.x !== x || translate.y !== y) {
      return setTranslate(function (param) {
                  return {
                          x: x,
                          y: y
                        };
                });
    }
    
  };
  return [
          translate,
          containerRef
        ];
}

var javascript = LangJavascript.javascript();

var vim = CodemirrorVim.vim();

var core = LanguageJs.core;

var coreLang = core();

function replaceEmojis(s) {
  return s.replace(":event:", "⚡").replace(":retry:", "🔁").replace(":check:", "🏗️").replace(":finish:", "✅").replace(":cancel:", "⏩").replace(":effects:", "⚙️").replace(":default:", "🔄");
}

function Editor(props) {
  var match = React.useState(function () {
        return sample;
      });
  var setCode = match[1];
  var code = match[0];
  var match$1 = React.useState(function () {
        return ReacttRace.run(0, code);
      });
  var setRecording = match$1[1];
  var recording = match$1[0];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setCurrentStep = match$2[1];
  var currentStep = match$2[0];
  var checkpoints = recording.checkpoints;
  var match$3;
  if (checkpoints !== undefined) {
    var tmp;
    if (currentStep === 0) {
      tmp = {};
    } else {
      var match$4 = checkpoints[currentStep - 1 | 0];
      tmp = match$4 !== undefined ? match$4.tree : ({});
    }
    match$3 = [
      checkpoints.map(function (x) {
                return replaceEmojis(x.msg);
              }).slice(0, currentStep).join("\n"),
      tmp,
      checkpoints.length
    ];
  } else {
    var error = recording.error;
    if (error !== undefined) {
      match$3 = [
        error,
        {},
        0
      ];
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "Editor.res",
              85,
              9
            ],
            Error: new Error()
          };
    }
  }
  var steps = match$3[2];
  var onChange = function (value) {
    setCode(function (param) {
          return value;
        });
    setCurrentStep(function (param) {
          return steps;
        });
    setRecording(function (param) {
          return ReacttRace.run(0, value);
        });
  };
  var match$5 = React.useState(function () {
        return false;
      });
  var setJSMode = match$5[1];
  var jsMode = match$5[0];
  var match$6 = React.useState(function () {
        return false;
      });
  var setVimMode = match$6[1];
  var vimMode = match$6[0];
  var extensions = [].concat(vimMode ? [vim] : [], jsMode ? [javascript] : [coreLang], [
        CodemirrorThemeTokyoNightDay.tokyoNightDay,
        HookLabelPlugin.plugin
      ]);
  var match$7 = useCenteredTree();
  return JsxRuntime.jsxs(Resizable.PanelGroup.make, {
              children: [
                JsxRuntime.jsx(Resizable.Panel.make, {
                      children: JsxRuntime.jsxs(Resizable.PanelGroup.make, {
                            children: [
                              JsxRuntime.jsx(Resizable.Panel.make, {
                                    children: JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx(Checkbox.make, {
                                                                  id: "check-vim-mode",
                                                                  checked: vimMode,
                                                                  onCheckedChange: (function (checked) {
                                                                      setVimMode(function (param) {
                                                                            return checked;
                                                                          });
                                                                    })
                                                                }),
                                                            JsxRuntime.jsx("label", {
                                                                  children: "Vim Keymap",
                                                                  className: "leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                                                                  htmlFor: "check-vim-mode"
                                                                })
                                                          ],
                                                          className: "flex gap-x-2"
                                                        }),
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx(Checkbox.make, {
                                                                  id: "check-js-mode",
                                                                  checked: jsMode,
                                                                  onCheckedChange: (function (checked) {
                                                                      setJSMode(function (param) {
                                                                            return checked;
                                                                          });
                                                                    })
                                                                }),
                                                            JsxRuntime.jsx("label", {
                                                                  children: "JS Syntax",
                                                                  className: "leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                                                                  htmlFor: "check-js-mode"
                                                                })
                                                          ],
                                                          className: "flex gap-x-2"
                                                        })
                                                  ],
                                                  className: "pb-1 pr-3 flex place-content-end items-center gap-x-4 text-sm font-medium"
                                                }),
                                            JsxRuntime.jsx(ReactCodemirror, {
                                                  value: code,
                                                  height: "100%",
                                                  onChange: onChange,
                                                  extensions: extensions,
                                                  className: "h-full text-base font-mono"
                                                })
                                          ],
                                          className: "flex h-full flex-col"
                                        })
                                  }),
                              JsxRuntime.jsx(Resizable.Handle.make, {
                                    withHandle: true
                                  }),
                              JsxRuntime.jsx(Resizable.Panel.make, {
                                    children: JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx(ReactD3Tree, {
                                                data: match$3[1],
                                                translate: match$7[0],
                                                orientation: "vertical"
                                              }),
                                          ref: Caml_option.some(match$7[1]),
                                          className: "rounded-lg h-full resize-y overflow-hidden border"
                                        })
                                  })
                            ],
                            direction: "horizontal"
                          })
                    }),
                JsxRuntime.jsx(Resizable.Handle.make, {
                      withHandle: true
                    }),
                JsxRuntime.jsx(Resizable.Panel.make, {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(Slider.make, {
                                    className: "w-full",
                                    value: [currentStep],
                                    onValueChange: (function (vs) {
                                        setCurrentStep(function (param) {
                                              return vs[0];
                                            });
                                      }),
                                    max: steps,
                                    step: 1
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: match$3[0],
                                    className: "text-base font-sans text-gray-800 whitespace-pre-wrap"
                                  })
                            ],
                            className: "flex flex-col h-full gap-4 p-3"
                          })
                    })
              ],
              direction: "vertical"
            });
}

var make = Editor;

export {
  sample ,
  useCenteredTree ,
  javascript ,
  vim ,
  core ,
  coreLang ,
  replaceEmojis ,
  make ,
}
/* sample Not a pure module */
