'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Skeleton from "./shadcn-ui/Skeleton.res.js";
import Dynamic from "next/dynamic";
import * as JsxRuntime from "react/jsx-runtime";

var lazyEditor = Dynamic((async function () {
        return await import("./Editor.res.js").then(function (m) {
                    return m.make;
                  });
      }), {
      ssr: false,
      loading: (function () {
          return JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Skeleton.make, {
                              className: "h-96"
                            }),
                        JsxRuntime.jsx(Skeleton.make, {
                              className: "h-48"
                            })
                      ],
                      className: "flex flex-col gap-4"
                    });
        })
    });

function Home(props) {
  var editor = React.createElement(lazyEditor, {});
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "React-tRace",
                      className: "text-4xl p-3 font-serif"
                    }),
                editor
              ],
              className: "flex h-screen flex-col"
            });
}

var make = Home;

export {
  lazyEditor ,
  make ,
}
/* lazyEditor Not a pure module */
