'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loading from "./Loading.res.js";
import Dynamic from "next/dynamic";
import * as JsxRuntime from "react/jsx-runtime";

var lazyEditor = Dynamic((async function () {
        return await import("./Editor.res.js").then(function (m) {
                    return m.make;
                  });
      }), {
      ssr: (process.env.NODE_ENV === 'development'),
      loading: (function () {
          return JsxRuntime.jsx(Loading.make, {});
        })
    });

function Home(props) {
  var editor = React.createElement(lazyEditor, {});
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "React-tRace",
                      className: "text-4xl font-serif"
                    }),
                editor
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Home;

export {
  lazyEditor ,
  make ,
}
/* lazyEditor Not a pure module */
