// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Loading(props) {
  return JsxRuntime.jsx("span", {
              children: "Loading..."
            });
}

var make = Loading;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
