// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactTraceBcJs from "./react-trace.bc.js";

function run(prim0, prim1) {
  return ReactTraceBcJs.run(prim0, prim1);
}

export {
  run ,
}
/* ./react-trace.bc.js Not a pure module */
