'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Checkbox from "./shadcn-ui/Checkbox.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as HookLabelPlugin from "../shared/plugin/HookLabelPlugin.res.js";
import * as ReacttRaceWrapper from "../shared/react-trace/ReacttRaceWrapper.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import ReactCodemirror from "@uiw/react-codemirror";
import * as CodemirrorVim from "@replit/codemirror-vim";
import * as LangJavascript from "@codemirror/lang-javascript";
import * as LanguageJs from "../shared/syntax/language.js";
import * as CodemirrorThemeTokyoNightDay from "@uiw/codemirror-theme-tokyo-night-day";

var sample = "\nlet C x =\n  let (s, setS) = useState x in\n  if s = 42 then\n    setS (fun s -> s + 1);\n  view [()]\n;;\nlet D _ =\n  let (s, setS) = useState true in\n  useEffect (setS (fun _ -> false));\n  view [C 42]\n;;\nview [D (), 0]\n".trim();

var javascript = LangJavascript.javascript();

var vim = CodemirrorVim.vim();

var core = LanguageJs.core;

var coreLang = core();

var fetchedReacttRace = {
  contents: undefined
};

function handleExn(run) {
  return function (fuel, value) {
    try {
      return run(fuel, value);
    }
    catch (raw_e){
      var e = Caml_js_exceptions.internalToOCamlException(raw_e);
      if (e.RE_EXN_ID === Js_exn.$$Error) {
        console.error(e._1);
        return "Runtime error";
      }
      throw e;
    }
  };
}

function reacttRace(fuel, value, setRecording) {
  var run = fetchedReacttRace.contents;
  if (run !== undefined) {
    return setRecording(function (param) {
                return run(fuel, value);
              });
  } else {
    ((async function () {
            var run = handleExn(await ReacttRaceWrapper.$$fetch());
            fetchedReacttRace.contents = run;
            return setRecording(function (param) {
                        return run(fuel, value);
                      });
          })());
    return ;
  }
}

function Editor(props) {
  var match = React.useState(function () {
        return sample;
      });
  var setValue = match[1];
  var value = match[0];
  var match$1 = React.useState(function () {
        return Core__Option.map(fetchedReacttRace.contents, (function (run) {
                      return run(0, value);
                    }));
      });
  var setRecording = match$1[1];
  var recording = match$1[0];
  React.useEffect((function () {
          if (Core__Option.isNone(recording)) {
            reacttRace(0, value, setRecording);
          }
          
        }), []);
  var onChange = function (value) {
    setValue(function (param) {
          return value;
        });
    reacttRace(0, value, setRecording);
  };
  var match$2 = React.useState(function () {
        return false;
      });
  var setJSMode = match$2[1];
  var jsMode = match$2[0];
  var match$3 = React.useState(function () {
        return false;
      });
  var setVimMode = match$3[1];
  var vimMode = match$3[0];
  var extensions = [].concat(vimMode ? [vim] : [], jsMode ? [javascript] : [coreLang], [
        CodemirrorThemeTokyoNightDay.tokyoNightDay,
        HookLabelPlugin.plugin
      ]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Checkbox.make, {
                                      id: "check-vim-mode",
                                      checked: vimMode,
                                      onCheckedChange: (function (checked) {
                                          setVimMode(function (param) {
                                                return checked;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("label", {
                                      children: "Vim Keymap",
                                      className: "leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                                      htmlFor: "check-vim-mode"
                                    })
                              ],
                              className: "flex space-x-2"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Checkbox.make, {
                                      id: "check-js-mode",
                                      checked: jsMode,
                                      onCheckedChange: (function (checked) {
                                          setJSMode(function (param) {
                                                return checked;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("label", {
                                      children: "JS Syntax",
                                      className: "leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                                      htmlFor: "check-js-mode"
                                    })
                              ],
                              className: "flex space-x-2"
                            })
                      ],
                      className: "flex place-self-end items-center space-x-4 text-sm font-medium"
                    }),
                JsxRuntime.jsx(ReactCodemirror, {
                      value: value,
                      onChange: onChange,
                      extensions: extensions,
                      className: "text-base font-mono"
                    }),
                JsxRuntime.jsx("div", {
                      children: Core__Option.getOr(recording, "Loading..."),
                      className: "text-lg font-sans text-gray-800 whitespace-pre-wrap"
                    })
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Editor;

export {
  sample ,
  javascript ,
  vim ,
  core ,
  coreLang ,
  fetchedReacttRace ,
  reacttRace ,
  make ,
}
/* sample Not a pure module */
