// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

async function make(param) {
  return JsxRuntime.jsx("div", {
              children: "Hello, React-tRace!",
              className: "flex flex-col gap-7"
            });
}

var Home = make;

var make$1 = Home;

export {
  make$1 as make,
}
/* react/jsx-runtime Not a pure module */
