// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Editor from "./Editor.res.js";
import * as JsxRuntime from "react/jsx-runtime";

async function make(param) {
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "React-tRace",
                      className: "text-4xl font-serif"
                    }),
                JsxRuntime.jsx(Editor.make, {})
              ],
              className: "flex flex-col gap-4"
            });
}

var Home = make;

var make$1 = Home;

export {
  make$1 as make,
}
/* Editor Not a pure module */
