'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Dynamic from "next/dynamic";
import * as JsxRuntime from "react/jsx-runtime";

async function make(param) {
  var lazyEditor = Dynamic((async function () {
          return await import("./Editor.res.js").then(function (m) {
                      return m.make;
                    });
        }), {
        ssr: false,
        loading: (function () {
            return JsxRuntime.jsx("span", {
                        children: "Loading..."
                      });
          })
      });
  var editor = React.createElement(lazyEditor, {});
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "React-tRace",
                      className: "text-4xl font-serif"
                    }),
                editor
              ],
              className: "flex flex-col gap-4"
            });
}

var Home = make;

var make$1 = Home;

export {
  make$1 as make,
}
/* react Not a pure module */
