// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Resizable from "./resizable";

var make = Resizable.ResizablePanelGroup;

var PanelGroup = {
  make: make
};

var make$1 = Resizable.ResizablePanel;

var Panel = {
  make: make$1
};

var make$2 = Resizable.ResizableHandle;

var Handle = {
  make: make$2
};

export {
  PanelGroup ,
  Panel ,
  Handle ,
}
/* make Not a pure module */
